language: node_js
node_js: 12.16.3
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_fbe94068f81d_key -iv $encrypted_fbe94068f81d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- npm install -g gitbook-cli
install: npm install
script: 
- gitbook install
- gitbook build
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@106.14.218.172 -o StrictHostKeyChecking=no 'sh publish.sh'
